@extends('layouts.app')

@section('content')
    <h2>Report Details</h2>
    <p><strong>Report Type:</strong> {{ $report->type }}</p>
    <p><strong>Period:</strong> {{ $report->period }}</p>
    <p><strong>Generated By:</strong> {{ $report->user->name }}</p>
    <p><strong>Generation Date:</strong> {{ $report->created_at->format('Y-m-d') }}</p>

    @if($report->type == 'income' || $report->type == 'profit')
        <p><strong>Total Income:</strong> {{ $report->total_income }}</p>
    @endif
    @if($report->type == 'expenses' || $report->type == 'profit')
        <p><strong>Total Expenses:</strong> {{ $report->total_expenses }}</p>
    @endif
    @if($report->type == 'profit')
        <p><strong>Profit:</strong> {{ $report->total_income - $report->total_expenses }}</p>
    @endif
    @if($report->type == 'monthly_budget_progress')
        <h3>Budget Progress</h3>
        @foreach($report->budgets as $budget)
            <p>{{ $budget->category }}: {{ $budget->current_expense }} / {{ $budget->budget_limit }}</p>
        @endforeach
    @endif
    @if($report->type == 'crediting')
        <h3>Credit Transactions</h3>
        @foreach($report->credit_transactions as $transaction)
            <p>{{ $transaction->type }} - Amount: {{ $transaction->amount }}</p>
        @endforeach
    @endif
    @if($report->type == 'failed_transactions')
        <h3>Failed Transactions</h3>
        @foreach($report->failed_transactions as $transaction)
            <p>Amount: {{ $transaction->amount }} - Reason: {{ $transaction->description }}</p>
        @endforeach
    @endif
@endsection
